apiVersion: v1
#Untuk manifest configmap
kind: ConfigMap

#identitas resource
metadata:
  name: mongo-config

#menyimpan informasi mengenai path data
data:
  mongodb.conf: |
    storage:
      dbPath:/data/db
