#Order service
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
    service: order
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: order

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecom-order
  labels:
    account: order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-v1
  labels:
    app: order
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v1
  template:
    metadata:
      labels:
        app: order
        version: v1
    spec:
      serviceAccountName: ecom-order
      containers:
      - name: order
        image: ghcr.io/willyardiyanto/order-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env: # Variabel lingkungan untuk kontainer
            - name: AMQP_URL
              value: ""

            - name: PORT
              value: "3000"

#Shipping service
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
    service: shipping
spec:
  ports:
  - port: 3001
    name: http
  selector:
    app: shipping

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecom-shipping
  labels:
    account: shipping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-v1
  labels:
    app: shipping
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
      version: v1
  template:
    metadata:
      labels:
        app: shipping
        version: v1
    spec:
      serviceAccountName: ecom-shipping
      containers:
      - name: shipping
        image: ghcr.io/willyardiyanto/shipping-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env: # Variabel lingkungan untuk kontainer
            - name: AMQP_URL
              value: ""

            - name: PORT
              value: "3001"