apiVersion: networking.istio.io/v1beta1  # Versi API Istio yang digunakan
kind: VirtualService  # Jenis objek yang didefinisikan dalam manifest ini (VirtualService Istio)

metadata:
  name: shipping-virtualservice  # Nama untuk VirtualService yang akan Anda buat
  namespace: istio-system  # Namespace di mana VirtualService akan diatur

spec:
  gateways:
    - shipping-gateway  # Menghubungkan VirtualService ini dengan gateway "shipping-gateway"

  hosts:
    - "*"  # VirtualService akan menerima permintaan dari semua host (Wildcard)

  http:
    - match:
        - uri:
            exact: /shipping  # Mengatur kondisi pencocokan untuk URI yang persis "/shipping"
      route:
        - destination:
            # host: shipping.dicoding.svc.cluster.local  # Nama host tujuan untuk rute
            host: shipping-service  # Nama host tujuan untuk rute (shiping-service)
            port:
              number: 80  # Nomor port untuk rute (port 3001)