apiVersion: networking.istio.io/v1beta1

kind: Gateway

metadata:
  name: order-gateway
  namespace: istio-system

spec:
  selector:
    istio: ingressgateway

  servers:
  - hosts:
    - order.anbutech.xyz

    port:
      name: http
      number: 80
      protocol: HTTP
