apiVersion: apps/v1
#untuk manifest deployment
kind: Deployment
metadata:
  name: karsajobs #atur nama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
        - name: karsajobs
          image: ghcr.io/willyardiyanto/karsajobs:latest #setting container image
          ports:
            - containerPort: 8080
          env: #setting environment
            - name: APP_PORT
              value: "8080"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_HOST
              value: karsajob-database
